### PR TITLE
Function Calling Rest API with Local Mistral7Bv3 using Ollama

### PR DESCRIPTION
**Pull request by sachinsshetty**
OpenAPI spec end-points consisting of Pet store information from edior.swagger.io .
Using function_calling - make RestAPI calls from local LLM

### CODE REVIEW

**Comment by sophiamyang** [comment]
Hi @sachinsshetty , thanks for the notebook! Could you add this to the Ollama folder https://github.com/mistralai/cookbook/tree/main/third_party/Ollama/? Thank you!

**Comment by sachinsshetty** [comment]
@sophiamyang changes are complete.
Also squash and merge would make the commit history clean. 
I've updated the Readme to use markdown file paths instead of url.

**Comment by sophiamyang** [comment]
Thank you! Merged!

**Comment by sophiamyang** [comment]
Hi @sachinsshetty, actually this notebook is not runnable on Colab. Would it be possible to make it runnable on colab?

**Comment by sachinsshetty** [comment]
Notebook requires access to Ollama server which is running locally or hosted in a server.

I will try to make it work with Google Colab.

**Pull request merged**
