### PR TITLE
UPDATE MISTRALAI SDK AND AZURE SEARCH SDK TO LATEST STABLE

### PR DESCRIPTION
**Pull request by farzad528**

### CODE REVIEW

**Comment by farzad528** [comment]
@Wendong-Fan @sophiamyang minor packaging update here on the MSFT side. Plz approve.

**Review by pandora-s-git — APPROVED** [review]

**Comment by pandora-s-git** [comment]
Looks good! Thank you! I've approved!

**Comment by farzad528** [comment]
@pandora-s-git thx. please merge

**Comment by pandora-s-git** [comment]
My bad! Merging!

**Pull request merged**
