### PR TITLE
Initiation MistralAI MongoDB notebook

### PR DESCRIPTION
**Pull request by cozypet**
Creating a LLM GenAI application integrates the power of Mistral AI with the robustness of an enterprise-grade vector store like MongoDB. Below is a detailed step-by-step guide to implementing this innovative system:

### CODE REVIEW

**Comment by sophiamyang** [comment]
Hi @cozypet thanks for the PR! Could you move the notebook to the third-party folder and could you make sure the notebook runs on colab? Thanks!

**Comment by cozypet** [comment]
Hello Sophia, just updated the notebook as requested.

**Comment by sophiamyang** [comment]
Hi @cozypet thanks so much for the updates! Did you make changes to the function_calling.ipynb file? I don't think the changes are needed?

**Comment by sophiamyang** [comment]
Also, could you add `!pip install xxx` to make sure the notebook is runnable on colab?

**Comment by cozypet** [comment]
Hello @sophiamyang just commit a new version

**Comment by sophiamyang** [comment]
Thanks so much @cozypet! Looks amazing. Just one small thing. Could you also help remove the changes to the .DS_Store file? Thanks!

**Comment by sophiamyang** [comment]
Hey @cozypet sorry I can't seem to reopen this PR. Could you make a new PR please? thank you!

**Pull request closed without merging**
