### PR TITLE
feat: add chainlit cookbook

### PR DESCRIPTION
**Pull request by desaxce**
# Changes
- Added a Chainlit cookbook illustrating Mistral's tool calling capabilities to answer multi-step reasoning questions

### CODE REVIEW

**Comment by pandora-s-git** [comment]
It looks good, maybe add a few imports and !pip install in the notebook just in case.

**Comment by desaxce** [comment]
> It looks good, maybe add a few imports and !pip install in the notebook just in case.

Good point, I've added a requirements section to the notebook with package installation.

**Comment by pandora-s-git** [comment]
Nice! Could you add it to the table in the readme?

**Comment by desaxce** [comment]
> Nice! Could you add it to the table in the readme?

Absolutely! Also sorted the table alphabetically on tool name. Let me know if you had something else in mind.

image

**Comment by sophiamyang** [comment]
Hi @desaxce , thanks so much for contributing to our cookbook! Would it be possible for you to add Mistral to your [docs](https://docs.chainlit.io/get-started/overview) as well?

**Comment by desaxce** [comment]
> Hi @desaxce , thanks so much for contributing to our cookbook! Would it be possible for you to add Mistral to your [docs](https://docs.chainlit.io/get-started/overview#integrations) as well?

No problem, I just added it - check it at https://docs.chainlit.io/get-started/overview#integrations

**Comment by sophiamyang** [comment]
Awesome! Thanks so much!

**Pull request merged**
